In [1]:
import numpy as np
np.random.rand(25)

array([0.56970825, 0.50731174, 0.04980768, 0.1298673 , 0.95773504,
       0.94064165, 0.65075186, 0.02310967, 0.10750534, 0.38837547,
       0.72635557, 0.26287465, 0.64387756, 0.72053802, 0.76902033,
       0.97283577, 0.74381697, 0.2057563 , 0.92807272, 0.99172183,
       0.16327667, 0.4131824 , 0.90518593, 0.3577671 , 0.74177108])

In [2]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [6]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [8]:
np.random.rand(100)

array([0.94637718, 0.77777802, 0.62457472, 0.4384315 , 0.14016054,
       0.53119832, 0.98044855, 0.17767858, 0.55284041, 0.95107164,
       0.54748979, 0.57876962, 0.3669838 , 0.06050299, 0.66843356,
       0.88948489, 0.17846373, 0.44890474, 0.73058757, 0.18594852,
       0.33750345, 0.04684863, 0.54651307, 0.14603325, 0.42715222,
       0.33302906, 0.81569231, 0.68547829, 0.61614551, 0.99766562,
       0.10821812, 0.01724455, 0.94988063, 0.75495168, 0.63539921,
       0.81723864, 0.39381576, 0.40247491, 0.05413398, 0.99354129,
       0.66692738, 0.54020838, 0.52627468, 0.74635879, 0.70622379,
       0.12294816, 0.86437994, 0.02683143, 0.88008315, 0.08256166,
       0.3236638 , 0.53115058, 0.00486456, 0.28814445, 0.84282123,
       0.58580549, 0.87339272, 0.62778591, 0.33505265, 0.85229519,
       0.30006598, 0.88153726, 0.54977631, 0.79917474, 0.69880038,
       0.92938359, 0.1921238 , 0.05766547, 0.55992041, 0.39568438,
       0.49957102, 0.30989346, 0.28562584, 0.51431587, 0.74424

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))